### ISSUE TITLE
Function 'get_der_fast' with 'bulk_mode = T'

### ISSUE THREAD

**Issue by jiazhao97** [dmcable/RCTD#10]
I applied RCTD on mouse brain data successfully, and found RCTD very useful when analyzing ST data.

Here I have one question about RCTD:

The way of implementing first and second order derivatives in function 'get_der_fast' with 'bulk_mode = T' is quite different from that with 'bulk_mode = F'. Does the function 'get_der_fast' with 'bulk_mode = T' adopt approximation? What kind of approximation does it use? 

```
if(bulk_mode) {
    #d1_vec <- -t(log(prediction) - log(B))
    #d2_vec <- -t(1/prediction)
    d1_vec <- -2*t((log(prediction) - log(B))/prediction)
    d2_vec <- -2*t((1 - log(prediction) + log(B))/prediction^2)
  } else {
    d1_d2 <- get_d1_d2(B, prediction)
    d1_vec <- d1_d2$d1_vec
    d2_vec <- d1_d2$d2_vec
  }
```

Thanks.

**Comment by dmcable** [comment]
I am glad you found it useful!

You are correct that it does adopt an approximation. Usually, I use bulk_mode=T for the "platform effect normalization" step in which all pixels are merged into a pseudo-bulk. For fitting individual pixels, I use bulk_mode = F. Here are the pros and cons of each method:

1) For bulk_mode=T, we assume that the counts of each gene is sufficiently large (i.e. >= 10 for most genes), so that Poisson sampling can be neglected. In this case, the objective function is (log(prediction) - log(B))^2 due to the log-normal random noise. 
2) For bulk_mode=F, we consider the Poisson-lognormal model. For speed, we use precomputed data values for 0 <= B <= K. If B > K, we simply set it to the maximum value K. Thus, for this mode, we assume that most genes do not get counted more than K times. By default, K is set to 100. In my experience, this value works well for Slide-seq and Visium on individual pixels. However, for the pseudo-bulk case, we can no longer assume that most genes are counted less than K, so we must employ the approximation.

Hope this helps!
Dylan

**Comment by jiazhao97** [comment]
It is clear for me now, thank you for your reply! :)
