### ISSUE TITLE
can not find the function 'init_RCTD'

### ISSUE THREAD

**Issue by XingjieShi** [dmcable/RCTD#13]
Hi there, thanks for sharing your codes.

I can not find the function 'init_RCTD' in Line 29 of file "RCTD/AnalysisPaper/MainFigures/figure2-platform-effect.Rmd":

iv <- init_RCTD(gene_list_reg = F, get_proportions = DropViz, load_info = F)

Error: object 'init_RCTD' not found

**Comment by dmcable** [comment]
Hi, I have posted a new [Rmd file](https://github.com/dmcable/RCTD/blob/dev/AnalysisPaper/MainFigures/Updated-Compatability/figure2-platform-effect.Rmd) updating this analysis script to be compatible with the most recent version of RCTD. 

The function `init_RCTD` has since been deprecated, and the new version of RCTD organizes all variables into the `RCTD` object. The script that you referenced was used to analyze results of an old version of RCTD. 

Please let me know if you have any further questions.

**Comment by XingjieShi** [comment]
Hi, thank you so much for the update and explanation. It was very helpful.
