### ISSUE TITLE
quick question about the mouse cerebellum data 

### ISSUE THREAD

**Issue by jakezhusph** [dmcable/RCTD#3]
Hi, I am currently trying the RCTD method on the mouse cerebellum data provided on the single cell portal. I was able to get the software running and obtain the results. However, the results I collected are different from the results presented in the paper in terms of the number of pixels confidently assigned. 

The data files I used are Cerebellum_MappedDGEForR.csv, Cerebellum_BeadLocationsForR.csv and reference file is the scRefSubsampled1000_cerebellum_singlenucleus.RDS.zip. I created a dataset.yml following the guide (point to the new dataset, and change the n_puck_folds=50) and used it in the function config::get(file = paste0(workdir,"/conf/dataset.yml"), use_parent = FALSE). 

There are 39,495 pixels in the original data, 27,195 pixels passing the UMI threshold (100) and 13,976 confident assigned pixels in the final result (12,254 singlet , 1722 double_certain).

Is there any data processing procedure I missed? or any misspecified parameter setting?

Thanks

**Comment by dmcable** [comment]
Hi, right, I think the issue is that the field of view was cropped before running RCTD. This is because some of the slide-seq data is outside of the cerebellum. If you would like, I would be happy to send you the list of bead barcodes that were included after cropping. Feel free to send me an email, and I can send you the file.

Dylan

**Comment by jakezhusph** [comment]
Great. My email is Jiaqiang@umich.edu. Thanks for your quick reply :)

Jake
