### ISSUE TITLE
Can't find the data set to replicate the results

### ISSUE THREAD

**Issue by zuoyi93** [dmcable/RCTD#36]
Dear Dr. Cable,

Thanks for sharing this amazing repository and it really helps understand the RCTD package!

However, I do have a few questions on how to reproduce the results in the paper using the RCTD package. First, I understand that [this portal](https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics#study-download) should have all of the data sets, but I still have difficulty locating most of them in the [AnalysisPaper](https://github.com/dmcable/RCTD/tree/master/AnalysisPaper) folder.

For example, I don't know how to generate the `myRCTD_cer.rds` file here. https://github.com/dmcable/RCTD/blob/e74fa3e612bf396cf0e4ce1f08abf9444fbf9082/AnalysisPaper/MainFigures/figure1.Rmd#L46

Also, I can't find the `scRefSubsampled1000.RDS` file on the portal. There are `scRefSubsampled1000_hippocampus.RDS` and `scRefSubsampled1000_cerebellum_singlenucleus.RDS` that look very similar, but I don't think they are exactly what we need here.

https://github.com/dmcable/RCTD/blob/e74fa3e612bf396cf0e4ce1f08abf9444fbf9082/AnalysisPaper/Rscripts/doubletsimulation.R#L6

My second question is, is there an order of how we should run the code in the [script](https://github.com/dmcable/RCTD/tree/master/AnalysisPaper/Rscripts) folder? Or it really does not matter?

In addition, I found that the `config_data$slideseqfolde` object down below is `NULL`.

https://github.com/dmcable/RCTD/blob/e74fa3e612bf396cf0e4ce1f08abf9444fbf9082/AnalysisPaper/Rscripts/prepareNMF.R#L5

Thanks in advance for your time!

Yi

**Comment by djgroso** [comment]
Hello,

I'm having a similar issue as Yi and wanted to see if there is any resolution. Thank you.

Daniel

**Comment by dmcable** [comment]
Dear Yi,

I am happy to share any extra files that weren't added to the single cell repository. In this case, the reason you are not seeing `myRCTD.rds` is because that was an intermediate file that was generated after running RCTD on the reference and spatialRNA objects. Therefore, the `myRCTD` object can be obtained by running RCTD. In any case, I have sent you an email containing the `myRCTD.rds` object.

The reference datasets `scRefSubsampled1000_hippocampus.RDS` and `scRefSubsampled1000_cerebellum_singlenucleus.RDS` are two different references used for the hippocampus and cerebellum analyses in our paper, respectively. That is, they are for two different tissue regions. Either of these files is the `scRefSubsampled1000.RDS` file you are looking for, depending on the dataset you would like to work with.

Most of the R-scripts in the `Rscripts` folder can run independently of each other, except, I believe, `prepareNMF.R`, which needs to run before `processNMF.R`.

The file location `config_data$slideseqfolder` can just be replaced with the directory you are storing the Slide-seq files on your computer. Please note that this `config_data` variable is from an earlier version of RCTD, which is currently outdated.

@djgroso , likewise, let me know if there are any files that are missing for you, in which case please include your email address.

**Comment by zuoyi93** [comment]
Dear Dr. Cable,

Thanks very much for your response, and I have received your file!

All the responses make sense to me and I will close the issue.

Best,

Yi

**Comment by vanhoan310** [comment]
Dear Dr. Cable,

Could you send data sets to me as well? My email address is vanhoan310@gmail.com.

Thanks,
Hoan

**Comment by dmcable** [comment]
Yes, sending it now!

**Comment by Vivianstats** [comment]
Dear Dylan,

I am trying to run RCTD following the vignette for the Cerebellum slide-seq data, but found that the sample data only contains ~100 spots. I wonder if you still have the full spatial data for this example and if you can share it with me?

Another question I have is there are still 19 columns in myRCTD@results$weights when running the doublet mode, but they do not add up to 1. The weights are not the same as cellular compositions?

Thank you very much for your time,
Vivian

**Comment by dmcable** [comment]
Dear Vivian,

Sure thing! At the Broad single cell portal (https://singlecell.broadinstitute.org/single_cell/study/SCP948), you can find the single-nucleus reference object (scRefSubsampled1000_cerebellum_singlenucleus.RDS.zip), the Slide-seq counts matrix (Cerebellum_MappedDGEForR.csv), and the Slide-seq coordinates matrix (Cerebellum_BeadLocationsForR.csv).

The weights are the same as cell type proportions, and can be normalized to sum to 1 (please see https://github.com/dmcable/RCTD/issues/45) for instructions on how to compute a normalized version of weights, `norm_weights`. Also, please see that discussion for the differences between full mode and doublet mode. In particular, although `myRCTD@results$weights` is generated during doublet mode, this 19 column matrix still represents the results of full mode.

Please let me know if you have any other questions.

Best,
Dylan

**Comment by Vivianstats** [comment]
Hi Dylan,

Thank you for the prompt reply!

I would like to confirm the cell cluster number as I saw 11 clusters instead of 19 in scRefSubsampled1000_cerebellum_singlenucleus.RDS

I also wonder if you have a file documenting the correspondence between cluster labels with cell type names, to reproduce results as shown in your Figure4?

**Comment by Vivianstats** [comment]
One more question about running RCTD on this example data: 

I tried to run `create.RCTD(spatial, reference)`, where `spatial` is constructed with `SpatialRNA()` and `reference` is the Seurat object imported from scRefSubsampled1000_cerebellum_singlenucleus.RDS.

However, the function encountered the following error:

> Error in levels(reference@cell_types) : 
  no slot of name "cell_types" for this object of class "Seurat"

I wonder what's the correct way to format the Seurat object? I didn't find such information on the function's help page

**Comment by dmcable** [comment]
Dear Vivian,

Ah, yes, it appears the objects on the Broad portal are out of data. I have sent you (email) the .rds object of the Reference object, which is compatible with RCTD. 

There should be 19 cell types, and the labeled names should appear in the Reference object.

Seurat objects are no longer used in the current version of RCTD. I hope this addresses your issues!

Best,
Dylan

**Comment by Vivianstats** [comment]
Hi Dylan,

Thanks a lot for sending the data. I got the following error when trying to import the rds file:

> Loading required package: DEGLAM
> Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘DEGLAM’

However, I was not able to find this package on CRAN/Bioconductor/Github.
Do you know how to fix this?

Best,
Vivian

**Comment by dmcable** [comment]
Dear Vivian,

Sorry about that -- the 'DEGLAM' package shouldn't be required for this object -- please try the new object that I just sent you. The issue should be fixed now.

Best,
Dylan

**Comment by Vivianstats** [comment]
Hi Dylan,

Thank you. The new data works! One more question:
There are more than 39,000 spots in the spatial data from Single Cell Portal, but you said you used around 11,000 in your paper. How were these spots selected?

**Comment by dmcable** [comment]
Hi Vivian, 

Spots were cropped to the region of interest (cerebellum). Please see the attached cropped SpatialRNA object. Thanks!

Best,
Dylan

[puckCropped_cer_rctd.rds.zip](https://github.com/dmcable/RCTD/files/7475085/puckCropped_cer_rctd.rds.zip)

**Comment by Vivianstats** [comment]
Hi Dylan, Thank you very much for the data and information! -Vivian
